version: '3.7'

services:

    reverse-proxy:
        image: nginx:1.19.1
        ports:
            - target: 80
              published: 80
              protocol: tcp
            - target: 443
              published: 443
              protocol: tcp
        secrets:
            - source: nginx-conf
              target: /etc/nginx/conf.d/default.conf
            - source: https-cert
              target: /etc/ssl/certs/my-cert.pem
            - source: https-key
              target: /etc/ssl/private/my-key.pem

secrets:
    https-cert:
        external: true
        name: forge-keeper-https-cert
    https-key:
        external: true
        name: forge-keeper-https-key
    nginx-conf:
        external: true
        name: forge-keeper-nginx-conf