version: '3.7'

services:

    reverse-proxy:
        image: nginx:1.19.1
        ports:
            - target: 80
              published: 80
              protocol: tcp
        secrets:
            - source: nginx-forward
              target: /etc/nginx/conf.d/default.conf

secrets:
    nginx-forward:
        external: true
        name: forge-keeper-nginx-forward
